// dados.js - Todos os livros em um array
const dadosLivros = [
  {"numero":"2","tipo":"PDF","instrumento":"DISSERTAÇÃO","autor":"KEYLA ROSA DE OLIVEIRA","titulo":"PANORAMA DA EDUCAÇÃO MUSICAL PRÁTICAS METODOLÓGICAS EM DUAS ESCOLAS DE MÚSICA DE GOIÂNIA GO","arquivo":"pdf/2.pdf"},
  {"numero":"3","tipo":"PDF","instrumento":"ARTIGO","autor":"HELENA CARRERAS CABEZAS","titulo":"CONSIDERAÇÕES SOBRE OS HORIZONTES PEDAGÓGICOS EM JÁTÉKOK, DE GYÖRGY KURTÁG","arquivo":"pdf/3.pdf"},
  {"numero":"4","tipo":"PDF","instrumento":"ARTIGO","autor":"MIGUEL SÁ","titulo":"ARRANJADOR UM PARCEIRO DA CANÇÃO","arquivo":"pdf/4.pdf"},
  {"numero":"5","tipo":"PDF","instrumento":"DISSERTAÇÃO","autor":"CARLOS ALBERTO SILVA","titulo":"VOZES, MÚSICA, AÇÃO DALCROZE EM CENA","arquivo":"pdf/5.pdf"},
  {"numero":"6","tipo":"PDF","instrumento":"FOLHETO","autor":"KODÁLY","titulo":"TE","arquivo":"pdf/6.pdf"},
  {"numero":"7","tipo":"PDF","instrumento":"MONOGRAFIA","autor":"CRISTIANE COSTA SOUSA","titulo":"O PASSO UM MÉTODO DE EDUCAÇÃO MUSICAL","arquivo":"pdf/7.pdf"},
  {"numero":"8","tipo":"PDF","instrumento":"REVISTA","autor":"TVESCOLA SALTO PARA O FUTURO","titulo":"EDUCAÇÃO MUSICAL ESCOLAR_ANO XXI BOLETIM 08","arquivo":"pdf/8.pdf"},
  {"numero":"9","tipo":"PDF","instrumento":"GUITARRA","autor":"Dave Celentano","titulo":"Killer Pentatonics","arquivo":"pdf/9.pdf"},
  {"numero":"10","tipo":"PDF","instrumento":"GUITARRA","autor":"Dave Celentano","titulo":"essential blues guitar lessons (74p)","arquivo":"pdf/10.pdf"},
  {"numero":"11","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"Acordes_Arpejos_E_Escalas","arquivo":"pdf/11.pdf"},
  {"numero":"12","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"Estudos para guitarra vol 4","arquivo":"pdf/12.pdf"},
  {"numero":"13","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"Estudos_para_guitarra_Vol_1","arquivo":"pdf/13.pdf"},
  {"numero":"14","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"Estudos_para_guitarra_vol_6_-*Harmonia_aplicada*(Chord_Melod","arquivo":"pdf/14.pdf"},
  {"numero":"15","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"A arte da improvisação","arquivo":"pdf/15.pdf"},
  {"numero":"16","tipo":"PDF","instrumento":"GUITARRA","autor":"Nelson Faria","titulo":"Brazilian Guitar Book","arquivo":"pdf/16.pdf"},
  {"numero":"17","tipo":"PDF","instrumento":"VIOLÃO","autor":"Pascual Roch","titulo":"method_volume_1","arquivo":"pdf/17.pdf"},
  {"numero":"18","tipo":"PDF","instrumento":"VIOLINO","autor":"DANCLA, Charles","titulo":"School_of_5_Pos_Bk_I_2-5_Positions_only Op.122","arquivo":"pdf/18.pdf"},
  {"numero":"19","tipo":"PDF","instrumento":"ÓRGÃO","autor":"PIANO","titulo":"CCB - Método Novo Estudos para Órgão Eletrônico","arquivo":"pdf/19.pdf"},
  {"numero":"20","tipo":"PDF","instrumento":"VIOLINO","autor":"DANCLA, Charles","titulo":"Op86_vnpart_jwhite","arquivo":"pdf/20.pdf"},
  {"numero":"21","tipo":"PDF","instrumento":"VIOLINO","autor":"DANCLA, Charles","titulo":"O_74","arquivo":"pdf/21.pdf"},
  {"numero":"22","tipo":"PDF","instrumento":"VIOLINO","autor":"DANCLA, Charles","titulo":"Op.123 Pet_ec_vl","arquivo":"pdf/22.pdf"},
  {"numero":"23","tipo":"PDF","instrumento":"PIANO-VIOLINO","autor":"DANCLA, Charles","titulo":"Op.123","arquivo":"pdf/23.pdf"},
  {"numero":"24","tipo":"PDF","instrumento":"PIANO-VIOLINO","autor":"DANCLA, Charles_Op.107","titulo":"Da_Les_Perles_p_sc_PDF","arquivo":"pdf/24.pdf"},
  {"numero":"25","tipo":"PDF","instrumento":"VIOLINO","autor":"DANCLA, Charles_Op.107","titulo":"Da_Les_Perles_p_sc_PDF_Les_Perles_violon.*PDF","arquivo":"pdf/25.pdf"},
  {"numero":"26","tipo":"PDF","instrumento":"VIOLINO DUO","autor":"DANCLA, Charles","titulo":"Op.128_mel_stud","arquivo":"pdf/26.pdf"},
  {"numero":"27","tipo":"PDF","instrumento":"VIOLÃO","autor":"João Pernambuco","titulo":"Sonho de Magia","arquivo":"pdf/27.pdf"},
  {"numero":"28","tipo":"PDF","instrumento":"LITERATURA","autor":"INSTITUTO ECOFUTURO","titulo":"Pra que serve a Literatura","arquivo":"pdf/28.pdf"},
  {"numero":"29","tipo":"PDF","instrumento":"FILOSOFIA","autor":"PLATÃO","titulo":"Republica","arquivo":"pdf/29.pdf"},
  {"numero":"30","tipo":"PDF","instrumento":"EMPREENDEDORISMO","autor":"Bel Pesce","titulo":"A Menina do Vale","arquivo":"pdf/30.pdf"},
  {"numero":"31","tipo":"PDF","instrumento":"EMPREENDEDORISMO","autor":"NATHALIE TRUTMANN","titulo":"Manual para jovens sonhadores","arquivo":"pdf/31.pdf"},
  {"numero":"32","tipo":"PDF","instrumento":"EMPREENDEDORISMO","autor":"Rita de Cássia da Costa Malheiros","titulo":"Viagem ao Mundo do Empreendedorismo","arquivo":"pdf/32.pdf"},
  {"numero":"33","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Ron Carter","titulo":"Building_Jazz_Bass_Lines","arquivo":"pdf/33.pdf"},
  {"numero":"34","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Arthur_Maia","titulo":"Transcriptions","arquivo":"pdf/34.pdf"},
  {"numero":"35","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Dan_Dean","titulo":"Metodo_Baixo BOOK 1","arquivo":"pdf/35.pdf"},
  {"numero":"36","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Patricio Galindo","titulo":"Lnn","arquivo":"pdf/36.pdf"},
  {"numero":"37","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Jim Stinnett","titulo":"Creating_Jazz_Bass_Lines","arquivo":"pdf/37.pdf"},
  {"numero":"38","tipo":"PDF","instrumento":"BATERIA -BAIXO","autor":"Cristiano Micalizzi","titulo":"Enciclopedia Dei Ritmi Per Batterie e Basso","arquivo":"pdf/38.pdf"},
  {"numero":"39","tipo":"PDF","instrumento":"PIANO","autor":"Mario Mascarenhas","titulo":"curso de piano vol. 1","arquivo":"pdf/39.pdf"},
  {"numero":"40","tipo":"PDF","instrumento":"PIANO","autor":"Burgmuller, F.","titulo":"25 Easy and Progressive Studies, Op 100","arquivo":"pdf/40.pdf"},
  {"numero":"41","tipo":"PDF","instrumento":"PIANO","autor":"Hanon C. L.","titulo":"The Virtuouso Pianist","arquivo":"pdf/41.pdf"},
  {"numero":"42","tipo":"PDF","instrumento":"EVANGÉLICO","autor":"SPURGEON, C. H.","titulo":"O CAMINHO DA SALVAÇÃO","arquivo":"pdf/42.pdf"},
  {"numero":"43","tipo":"PDF","instrumento":"MONOGRAFIA","autor":"DELCI ALVES DE SOUZA","titulo":"MUSICOTERAPIA: CONHECIMENTO, EQUILÍBRIO, SAÚDE MENTAL E BEM ESTAR","arquivo":"pdf/43.pdf"},
  {"numero":"44","tipo":"PDF","instrumento":"PIANO","autor":"ALFRED","titulo":"Dicionário_De_Acordes_Para_Piano","arquivo":"pdf/44.pdf"},
  {"numero":"45","tipo":"PDF","instrumento":"VIOLÃO","autor":"Luiz Henrique","titulo":"Apostila_de_violao","arquivo":"pdf/45.pdf"},
  {"numero":"46","tipo":"PDF","instrumento":"PROJETO","autor":"PROJETO SACI ARTE","titulo":"PROJETO DE INICIAÇÃO MUSICAL","arquivo":"pdf/46.pdf"},
  {"numero":"47","tipo":"PDF","instrumento":"FLAUTA DOCE","autor":"ALBERTINO MOURA BARBOSA FILHO","titulo":"MÚSICAS EVANGÉLICAS VOL 1","arquivo":"pdf/47.pdf"},
  {"numero":"48","tipo":"PDF","instrumento":"TROMPETE","autor":"ARBAN, J. B.","titulo":"Complete_Conservatory_Method_for_Trumpet","arquivo":"pdf/48.pdf"},
  {"numero":"49","tipo":"PDF","instrumento":"TROMPETE","autor":"Paul C. Herfurth","titulo":"A TUNE A DAY FOR TRUMPET vol 1 & 2","arquivo":"pdf/49.pdf"},
  {"numero":"50","tipo":"PDF","instrumento":"TROMPETE","autor":"ARBAN, J. B.","titulo":"Method_for_Trumpet","arquivo":"pdf/50.pdf"},
  {"numero":"51","tipo":"PDF","instrumento":"TROMPETE","autor":"PROJETO FORTALECIMENTO MUSICAL","titulo":"MÉTODO BÁSICO PARA TROMPETE","arquivo":"pdf/51.pdf"},
  {"numero":"52","tipo":"PDF","instrumento":"TROMPETE","autor":"AMADEU RUSSO","titulo":"MÉTODO DE PISTÃO, TROMBONE E BOMBARDINO","arquivo":"pdf/52.pdf"},
  {"numero":"53","tipo":"PDF","instrumento":"SAX TENOR","autor":"Sandy Feldstein","titulo":"Yamaha Band Student","arquivo":"pdf/53.pdf"},
  {"numero":"54","tipo":"PDF","instrumento":"STUDIO","autor":"DANILO GUSTAVO","titulo":"COMO MONTAR UM HOME STUDIO","arquivo":"pdf/54.pdf"},
  {"numero":"55","tipo":"PDF","instrumento":"PSICOLOGIA","autor":"VIVER DE BLOG","titulo":"O PODER DAS CORES NO MARKETING E NO DIA-A-DIA","arquivo":"pdf/55.pdf"},
  {"numero":"56","tipo":"PDF","instrumento":"VIOLÃO","autor":"HAL LEONARD","titulo":"CATÁLOGO CLASSICAL GUITAR","arquivo":"pdf/56.pdf"},
  {"numero":"57","tipo":"PDF","instrumento":"INSTRUMENTS","autor":"PARTITURAS.PT","titulo":"CATÁLOGO DE LIVROS DE INSTRUMENTOS MUSICAIS","arquivo":"pdf/57.pdf"},
  {"numero":"58","tipo":"PDF","instrumento":"MELODIA CIFRAS","autor":"CAETAANO VELOSO","titulo":"VOCÊ É LINDA","arquivo":"pdf/58.pdf"},
  {"numero":"59","tipo":"PDF","instrumento":"PIANO","autor":"DEBUSSY","titulo":"REVERIE","arquivo":"pdf/59.pdf"},
  {"numero":"60","tipo":"PDF","instrumento":"VIOLINO, VIOLONCELLO","autor":"BERENS HERM.","titulo":"GRESELLSCHAFTS QUARTETT -Op. 72","arquivo":"pdf/60.pdf"},
  {"numero":"61","tipo":"PDF","instrumento":"CEEP","autor":"ALBERTINO MOURA BARBOSA FILHO","titulo":"BIOTÉRIO ATIREI O PAU NO GATO","arquivo":"pdf/61.pdf"},
  {"numero":"62","tipo":"PDF","instrumento":"ARTIGO","autor":"PIANO","titulo":"TARCÍSIO GOMES FILHO","arquivo":"pdf/62.pdf"},
  {"numero":"63","tipo":"PDF","instrumento":"ARTIGO","autor":"PIANO","titulo":"JÚNIA GONÇALVES SANTIAGO -PROGRESSÃO DA DIFICULDADE TÉCNICA NAS TRÊS SUÍTES BRASILEIRAS PARA PIANO DE OSCAR LORENZO FERNÂNDEZ","arquivo":"pdf/63.pdf"},
  {"numero":"64","tipo":"PDF","instrumento":"PIANO","autor":"CONSERVATÓRIO DE MÚSICA CALOUSTE GULBENKIAN DE BRAGA","titulo":"PROGRAMA OFICIAL DE PIANO","arquivo":"pdf/64.pdf"},
  {"numero":"65","tipo":"PDF","instrumento":"PIANO","autor":"ESCOLA DE MÚSICA DO CONSERVATÓRIO NACIONAL","titulo":"PROGRAMAS DE PIANO","arquivo":"pdf/65.pdf"},
  {"numero":"66","tipo":"PDF","instrumento":"PIANO","autor":"UFRGS","titulo":"ESTUDOS E EXERCÍCIOS PARA PIANO","arquivo":"pdf/66.pdf"},
  {"numero":"67","tipo":"PDF","instrumento":"HARMONIA","autor":"ALAN GOMES","titulo":"Curso_de_harmonia_1_Net_Cursos","arquivo":"pdf/67.pdf"},
  {"numero":"68","tipo":"PDF","instrumento":"HARMONIA","autor":"MARIA LÚCIA PASCAL","titulo":"ESTRUTURA TONAL HARMONIA","arquivo":"pdf/68.pdf"},
  {"numero":"69","tipo":"PDF","instrumento":"TEORIA","autor":"ANTENOR DE CARVALHO NETO","titulo":"DOMINANTES SECUNDÁRIOS","arquivo":"pdf/69.pdf"},
  {"numero":"70","tipo":"PDF","instrumento":"HARMONIA","autor":"MANTOOTH,  F.","titulo":"Jazz Piano Voicings Mantooth","arquivo":"pdf/70.pdf"},
  {"numero":"71","tipo":"PDF","instrumento":"HARMONIA","autor":"Dave Cazier","titulo":"Jazz Piano Voicings","arquivo":"pdf/71.pdf"},
  {"numero":"72","tipo":"PDF","instrumento":"HARMONIA","autor":"Bob Keller","titulo":"Rootless Voicings for Jazz","arquivo":"pdf/72.pdf"},
  {"numero":"73","tipo":"PDF","instrumento":"SESI","autor":"GUIA DO ALUNO","titulo":"Guia_do_Aluno_cursos_modulares","arquivo":"pdf/73.pdf"},
  {"numero":"74","tipo":"PDF","instrumento":"CERTIFICADO","autor":"SEBRAE","titulo":"AE 06-09-13 certificado_sebrae.pdf2","arquivo":"pdf/74.pdf"},
  {"numero":"75","tipo":"PDF","instrumento":"CERTIFICADO","autor":"SEBRAE","titulo":"MEI 06-09-13 certificado_sebrae.pdf1","arquivo":"pdf/75.pdf"},
  {"numero":"76","tipo":"PDF","instrumento":"CERTIFICADO","autor":"SEBRAE","titulo":"IPGN 06-09-13 certificado_sebrae.pdf3","arquivo":"pdf/76.pdf"},
  {"numero":"77","tipo":"PDF","instrumento":"CERTIFICADO","autor":"SEBRAE","titulo":"SCD 06-09-13 certificado_sebrae.pdf4","arquivo":"pdf/77.pdf"},
  {"numero":"78","tipo":"PDF","instrumento":"HARMONIA","autor":"ALAN GOMES","titulo":"Curso_de_harmonia_2_Net_Cursos","arquivo":"pdf/78.pdf"},
  {"numero":"79","tipo":"PDF","instrumento":"TEORIA","autor":"BUHUMIL MED","titulo":"buhumil med","arquivo":"pdf/79.pdf"},
  {"numero":"80","tipo":"PDF","instrumento":"TEORIA","autor":"KOELLREUTTER H. J.","titulo":"Contraponto Modal do Séc XVI","arquivo":"pdf/80.pdf"},
  {"numero":"81","tipo":"PDF","instrumento":"PIANO","autor":"Livro","titulo":"Edna Mae Burnam - A dozen a day","arquivo":"pdf/81.pdf"},
  {"numero":"82","tipo":"PDF","instrumento":"PIANO","autor":"BERENS","titulo":"Berens","arquivo":"pdf/82.pdf"},
  {"numero":"83","tipo":"PDF","instrumento":"PIANO","autor":"Czerny","titulo":"Selected_Pianoforte_Studies_-_Book_I_-_Part_I_&_II_-_Edition_Germer","arquivo":"pdf/83.pdf"},
  {"numero":"84","tipo":"PDF","instrumento":"PIANO","autor":"Herz","titulo":"Gammes et Exercices","arquivo":"pdf/84.pdf"},
  {"numero":"85","tipo":"PDF","instrumento":"PIANO","autor":"Philipp","titulo":"Complete School of Technic for the Piano","arquivo":"pdf/85.pdf"},
  {"numero":"86","tipo":"PDF","instrumento":"PIANO","autor":"Plaidy","titulo":"Technical Studies","arquivo":"pdf/86.pdf"},
  {"numero":"87","tipo":"PDF","instrumento":"SAXOFONE","autor":"AMADEU RUSSO","titulo":"SAXOFONE-METODO-Amadeu-Russo","arquivo":"pdf/87.pdf"},
  {"numero":"88","tipo":"PDF","instrumento":"ÓRGÃO","autor":"PIANO","titulo":"CCB - Método Novo Estudos para Órgão Eletrônico","arquivo":"pdf/88.pdf"},
  {"numero":"89","tipo":"PDF","instrumento":"TEORIA","autor":"IAN GUEST","titulo":"CURSO DE Arranjo","arquivo":"pdf/89.pdf"},
  {"numero":"90","tipo":"PDF","instrumento":"EVANGÉLICO","autor":"João Alexandre","titulo":"\"Ferramentas Para Equipes de Música na Igreja” Módulo I","arquivo":"pdf/90.pdf"},
  {"numero":"91","tipo":"PDF","instrumento":"PIANO","autor":"Alfred's","titulo":"Basic Piano Library - All-in-one Course","arquivo":"pdf/91.pdf"},
  {"numero":"92","tipo":"PDF","instrumento":"PIANO","autor":"Alfred's","titulo":"Premier Piano Course","arquivo":"pdf/92.pdf"},
  {"numero":"93","tipo":"PDF","instrumento":"PIANO","autor":"Alfred's","titulo":"Premier Piano Course","arquivo":"pdf/93.pdf"},
  {"numero":"94","tipo":"PDF","instrumento":"PIANO","autor":"Alfred's","titulo":"Premier Piano Course","arquivo":"pdf/94.pdf"},
  {"numero":"95","tipo":"PDF","instrumento":"PIANO","autor":"Alfred's","titulo":"Teach Yourself To Play Piano","arquivo":"pdf/95.pdf"},
  {"numero":"96","tipo":"PDF","instrumento":"PIANO VOCAL","autor":"Debussy","titulo":"Les_ang__lus__voice_and_piano_","arquivo":"pdf/96.pdf"},
  {"numero":"97","tipo":"PDF","instrumento":"PIANO VOCAL","autor":"Debussy","titulo":"Aimons-nous_et_Dormons__voice_and_piano_","arquivo":"pdf/97.pdf"},
  {"numero":"98","tipo":"PDF","instrumento":"PIANO","autor":"Albert Ammons","titulo":"5 Boogie Woogie by","arquivo":"pdf/98.pdf"},
  {"numero":"99","tipo":"PDF","instrumento":"PIANO","autor":"Albert Ammons","titulo":"Monday Struggle","arquivo":"pdf/99.pdf"},
  {"numero":"100","tipo":"PDF","instrumento":"PIANO","autor":"Albert Ammons","titulo":"Shout For Joy","arquivo":"pdf/100.pdf"},
  {"numero":"101","tipo":"PDF","instrumento":"CERTIFICADO","autor":"MUSICAL CURSOS","titulo":"certificado","arquivo":"pdf/101.pdf"},
  {"numero":"102","tipo":"PDF","instrumento":"TEORIA","autor":"MIGUEL URTADO","titulo":"CLAVE","arquivo":"pdf/102.pdf"},
  {"numero":"103","tipo":"PDF","instrumento":"TEORIA","autor":"MIGUEL URTADO","titulo":"COMPASSO","arquivo":"pdf/103.pdf"},
  {"numero":"104","tipo":"PDF","instrumento":"TEORIA","autor":"MIGUEL URTADO","titulo":"duração","arquivo":"pdf/104.pdf"},
  {"numero":"105","tipo":"PDF","instrumento":"TEORIA","autor":"MIGUEL URTADO","titulo":"ligadura","arquivo":"pdf/105.pdf"},
  {"numero":"106","tipo":"PDF","instrumento":"TEORIA","autor":"MIGUEL URTADO","titulo":"parte_1","arquivo":"pdf/106.pdf"},
  {"numero":"107","tipo":"PDF","instrumento":"Metodologia do Trabalho Cientifico","autor":"Cleber Cristiano Prodanov","titulo":"Métodos e técnicas da pesquisa e do trabalho acadêmico","arquivo":"pdf/107.pdf"},
  {"numero":"108","tipo":"PDF","instrumento":"Pesquisa Bibliográfica","autor":"Agma Juci Machado Traina","titulo":"como Fazer Pesquisas Bibliograficas","arquivo":"pdf/108.pdf"},
  {"numero":"109","tipo":"PDF","instrumento":"ARTIGO","autor":"Patricia Costa","titulo":"Coro juvenil nas escolas: sonho ou possibilidade?","arquivo":"pdf/109.pdf"},
  {"numero":"110","tipo":"PDF","instrumento":"ARTIGO","autor":"Jorge Luiz Schroeder","titulo":"OS SABERES MUSICAIS E A ESCOLA","arquivo":"pdf/110.pdf"},
  {"numero":"111","tipo":"PDF","instrumento":"ARTIGO","autor":"JOSIANE DE ASSIS BUENO","titulo":"SABERES MUSICAIS COMPARTILHADOS: ETNOMUSICOLOGIA E INTERVIVÊNCIAS UNIVERSITÁRIAS COM JOVENS QUILOMBOLAS DO RIO GRANDE DO SUL.","arquivo":"pdf/111.pdf"},
  {"numero":"112","tipo":"PDF","instrumento":"ARTIGO","autor":"Cecília Cavalieri França","titulo":"Sopa de letrinhas notações analógicas (des)construindo a forma musical","arquivo":"pdf/112.pdf"},
  {"numero":"113","tipo":"PDF","instrumento":"VIOLONCELO","autor":"Davydov","titulo":"Russian School of Cello","arquivo":"pdf/113.pdf"},
  {"numero":"114","tipo":"PDF","instrumento":"VIOLONCELO","autor":"Paul C. Herfurth","titulo":"A Tune a Day for Cello vol 01","arquivo":"pdf/114.pdf"},
  {"numero":"115","tipo":"PDF","instrumento":"VIOLONCELO","autor":"Paul C. Herfurth","titulo":"A Tune a Day For Cello vol 02","arquivo":"pdf/115.pdf"},
  {"numero":"116","tipo":"PDF","instrumento":"VIOLONCELO","autor":"Sebastian Lee","titulo":"Metodo Sebastian Lee 40 Melodic Studies Book 1","arquivo":"pdf/116.pdf"},
  {"numero":"117","tipo":"PDF","instrumento":"VIOLONCELO","autor":"Sebastian Lee","titulo":"Metodo Sebastian Lee 40 Melodic Studies Book 2","arquivo":"pdf/117.pdf"},
  {"numero":"118","tipo":"PDF","instrumento":"CLARINETE","autor":"Mike Steinel","titulo":"Essential Elements","arquivo":"pdf/118.pdf"},
  {"numero":"119","tipo":"PDF","instrumento":"CLARINETE","autor":"Paul C. Herfurth","titulo":"A Tune a Day for Clarinet","arquivo":"pdf/119.pdf"},
  {"numero":"120","tipo":"PDF","instrumento":"CLARINETE","autor":"Paul C. Herfurth","titulo":"A Tune a Day for Clarinet","arquivo":"pdf/120.pdf"},
  {"numero":"121","tipo":"PDF","instrumento":"CLARINETE","autor":"Centre for New Zealand Music","titulo":"PROGRAMA DE CURSO","arquivo":"pdf/121.pdf"},
  {"numero":"122","tipo":"PDF","instrumento":"CLARINETE BASS","autor":"Essential Elements","titulo":"Bb Bass Clarinet","arquivo":"pdf/122.pdf"},
  {"numero":"123","tipo":"PDF","instrumento":"CLARINETE BASS","autor":"Essential Elements","titulo":"Bb Bass Clarinet","arquivo":"pdf/123.pdf"},
  {"numero":"124","tipo":"PDF","instrumento":"CLARINETE BASS","autor":"Bb Bass Clarinet","titulo":"Book 3","arquivo":"pdf/124.pdf"},
  {"numero":"125","tipo":"PDF","instrumento":"CLARINETE ALTO Eb","autor":"Essential Elements","titulo":"Eb Alto Clarinet","arquivo":"pdf/125.pdf"},
  {"numero":"126","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"Slap com Ritmos Brasileiros","titulo":"Adriano Giffoni","arquivo":"pdf/126.pdf"},
  {"numero":"127","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"slap","titulo":"celso pixinga","arquivo":"pdf/127.pdf"},
  {"numero":"128","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"rock","titulo":"fabio zaganin","arquivo":"pdf/128.pdf"},
  {"numero":"129","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"Harmonia e Teoria","titulo":"Thiago Spada","arquivo":"pdf/129.pdf"},
  {"numero":"130","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"conceitos para improvisação","titulo":"geraldo vieira","arquivo":"pdf/130.pdf"},
  {"numero":"131","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"conceitos para improvisação","titulo":"du moreira","arquivo":"pdf/131.pdf"},
  {"numero":"132","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Toque de Mestre","titulo":"Método Fundamentos Contra-Baixo Ronaldo Lobo","arquivo":"pdf/132.pdf"},
  {"numero":"133","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Toque de Mestre","titulo":"harmonia_para_contrabaixo_- Ivan Barasnevicius","arquivo":"pdf/133.pdf"},
  {"numero":"134","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"Triplo Dominio","titulo":"Chico Gomes","arquivo":"pdf/134.pdf"},
  {"numero":"135","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO -Toque de Mestre","autor":"Soul,*Funk*&*Disco","titulo":"Fernando Savaglia","arquivo":"pdf/135.pdf"},
  {"numero":"136","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"PHIL MULFORD","titulo":"The Complete Bass Player Book 1","arquivo":"pdf/136.pdf"},
  {"numero":"137","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"PHIL MULFORD","titulo":"The Complete Bass Player Book 2","arquivo":"pdf/137.pdf"},
  {"numero":"138","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"JORGE PESCARA","titulo":"Manual do groove para contra baixo","arquivo":"pdf/138.pdf"},
  {"numero":"139","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"MÁRCIO IGREJA","titulo":"Curso de Contra Baixo","arquivo":"pdf/139.pdf"},
  {"numero":"140","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"COVER BAIXO","titulo":"cover baixo escalas","arquivo":"pdf/140.pdf"},
  {"numero":"141","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"JORGE PESCARA","titulo":"Contrabaixo completo para iniciantes","arquivo":"pdf/141.pdf"},
  {"numero":"142","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"COLEÇÃO MUSICAL CONTRABAIXO","titulo":"Contra Baixo Especial","arquivo":"pdf/142.pdf"},
  {"numero":"143","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"ROBERTO WILLAM","titulo":"Baixo_Tapping","arquivo":"pdf/143.pdf"},
  {"numero":"144","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Dan_Dean","titulo":"baixo eletrico composite vol II","arquivo":"pdf/144.pdf"},
  {"numero":"145","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Dan_Dean","titulo":"baixo eletrico composite vol III","arquivo":"pdf/145.pdf"},
  {"numero":"146","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"BLOCO 3.COM","titulo":"Apostila de Contra-baixo","arquivo":"pdf/146.pdf"},
  {"numero":"147","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Nico Assumpção","titulo":"Bass Solo","arquivo":"pdf/147.pdf"},
  {"numero":"148","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Paul C. Herfurth","titulo":"A Tune a Day Flauta 2","arquivo":"pdf/148.pdf"},
  {"numero":"149","tipo":"PDF","instrumento":"FLAUTA DOCE BAIXO","autor":"OUTROS","titulo":"Método Flauta Doce Baixo","arquivo":"pdf/149.pdf"},
  {"numero":"150","tipo":"PDF","instrumento":"GUITARRA","autor":"Will Schimid","titulo":"Guitar Method (Will Schimid)","arquivo":"pdf/150.pdf"},
  {"numero":"151","tipo":"PDF","instrumento":"GUITARRA","autor":"RALPH AGRESTA","titulo":"Guitar Method Volumw Two","arquivo":"pdf/151.pdf"},
  {"numero":"152","tipo":"PDF","instrumento":"GUITARRA","autor":"JOHN TAPELLA","titulo":"Guitar Styles of the '90s","arquivo":"pdf/152.pdf"},
  {"numero":"153","tipo":"PDF","instrumento":"CONTRABAIXO","autor":"Jon Liebman","titulo":"Funk Fusion Bass","arquivo":"pdf/153.pdf"},
  {"numero":"154","tipo":"PDF","instrumento":"PEDAGOGIA MUSICAL","autor":"Swanwick, Keith","titulo":"ensinando música musicalmente","arquivo":"pdf/154.pdf"},
  {"numero":"155","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"JAMEY AEBERSOLD","titulo":"Bossa Novas for instrumentalists & vocalists","arquivo":"pdf/155.pdf"},
  {"numero":"156","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"CPAD","titulo":"harpa crista cifrada cpad","arquivo":"pdf/156.pdf"},
  {"numero":"157","tipo":"PDF","instrumento":"OBOÉ","autor":"Paul C. Herfurth","titulo":"A Tune a Day for Oboé vol1 e 2","arquivo":"pdf/157.pdf"},
  {"numero":"158","tipo":"PDF","instrumento":"PERCEPÇÃO","autor":"PRINCE, ADAMO","titulo":"PRINCE-1","arquivo":"pdf/158.pdf"},
  {"numero":"159","tipo":"PDF","instrumento":"PERCEPÇÃO","autor":"PRINCE, ADAMO","titulo":"PRINCE-2","arquivo":"pdf/159.pdf"},
  {"numero":"160","tipo":"PDF","instrumento":"PERCEPÇÃO","autor":"PRINCE, ADAMO","titulo":"PRINCE-3","arquivo":"pdf/160.pdf"},
  {"numero":"161","tipo":"PDF","instrumento":"PERCUSSÃO","autor":"Edgard Rocca","titulo":"Apostila de Percussão","arquivo":"pdf/161.pdf"},
  {"numero":"162","tipo":"PDF","instrumento":"PIANO","autor":"Ana Carolina Nunes do Couto","titulo":"APOSTILA DE PIANO EM GRUPO I","arquivo":"pdf/162.pdf"},
  {"numero":"163","tipo":"PDF","instrumento":"PIANO","autor":"Ana Carolina Nunes do Couto","titulo":"APOSTILA DE PIANO EM GRUPO II","arquivo":"pdf/163.pdf"},
  {"numero":"164","tipo":"PDF","instrumento":"PIANO","autor":"COLETÂNEA","titulo":"50 Popular Songs","arquivo":"pdf/164.pdf"},
  {"numero":"165","tipo":"PDF","instrumento":"TECLADO","autor":"NILSON FERREIRA","titulo":"Metodo para teclado","arquivo":"pdf/165.pdf"},
  {"numero":"166","tipo":"PDF","instrumento":"PIANO","autor":"CAROL BARRATT","titulo":"Chester's Easiest Piano Course Vol.3","arquivo":"pdf/166.pdf"},
  {"numero":"167","tipo":"PDF","instrumento":"PIANO","autor":"CAROL BARRATT","titulo":"Chester's Easiest Piano Course","arquivo":"pdf/167.pdf"},
  {"numero":"168","tipo":"PDF","instrumento":"PIANO","autor":"COLETÂNEA","titulo":"Classical Book 1 Creative Keyboard","arquivo":"pdf/168.pdf"},
  {"numero":"169","tipo":"PDF","instrumento":"PIANO","autor":"COLETÂNEA","titulo":"creative keyboard for all keyboards","arquivo":"pdf/169.pdf"},
  {"numero":"170","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Peter O'Mara","titulo":"Rhythmic Concept Funk FusionBass Peter O'Mara","arquivo":"pdf/170.pdf"},
  {"numero":"171","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Anibal Garcia","titulo":"Compendio do baixo elétrico","arquivo":"pdf/171.pdf"},
  {"numero":"172","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Alexandre Marrom","titulo":"Apostila de Contra-Baixo","arquivo":"pdf/172.pdf"},
  {"numero":"173","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA Capriccio_di_Bravura*-*Contrabaixo_e_piano*-_rev.*Streicher","arquivo":"pdf/173.pdf"},
  {"numero":"174","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Bottesini*-*Gran_Duetto_No_2_para_Dois_Contrabaixos*-_Rev.*Slatford","arquivo":"pdf/174.pdf"},
  {"numero":"175","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Bottesini*-*Melodia","arquivo":"pdf/175.pdf"},
  {"numero":"176","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Bottesini*-*Passione_Amorosa*-*Contrabaixo_I_and_II","arquivo":"pdf/176.pdf"},
  {"numero":"177","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Yorke_Complete_Bottesini*-*Contrabaixo_e_Piano*-*Parte_C.B.*-*Volume_1","arquivo":"pdf/177.pdf"},
  {"numero":"178","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Yorke_Complete_Bottesini*-*Contrabaixo_e_Piano*-*Parte_C.B.*-*Volume_2","arquivo":"pdf/178.pdf"},
  {"numero":"179","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Bottesini","titulo":"PARTITURA*-*Yorke_Complete_Bottesini*-*Contrabaixo_e_Piano*-*Parte_C.B.*-*Volume_3","arquivo":"pdf/179.pdf"},
  {"numero":"180","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Adriano Giffoni","titulo":"Música Brasileira Para Contrabaixo","arquivo":"pdf/180.pdf"},
  {"numero":"181","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Adriano Giffoni","titulo":"Música Brasileira Para Contrabaixo","arquivo":"pdf/181.pdf"},
  {"numero":"182","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Cláudio Santoro","titulo":"Fantasia Sul America for Double Bass","arquivo":"pdf/182.pdf"},
  {"numero":"183","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"COLEÇÃO","titulo":"Bass_Tab_White_Pages","arquivo":"pdf/183.pdf"},
  {"numero":"184","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Dragonetti Dominico","titulo":"ESTUDOS*-*Dragonetti*-*5_Estudos_Solo","arquivo":"pdf/184.pdf"},
  {"numero":"185","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"RABBATH, Francois","titulo":"MÉTODO","arquivo":"pdf/185.pdf"},
  {"numero":"186","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"RABBATH, Francois","titulo":"PARTITURA","arquivo":"pdf/186.pdf"},
  {"numero":"187","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"GLIÈRE, Reinhold","titulo":"PARTITURA_Gliere_4_peças_para_Contrabaixo_e_piano_ed.*Kalmus","arquivo":"pdf/187.pdf"},
  {"numero":"188","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Gustavo Menezes","titulo":"Aulas","arquivo":"pdf/188.pdf"},
  {"numero":"189","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Jaco Pastorius","titulo":"Modern Electric Bass","arquivo":"pdf/189.pdf"},
  {"numero":"190","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Jaco Pastorius","titulo":"The_Greates_Jazz-Fusion_Bass_Player","arquivo":"pdf/190.pdf"},
  {"numero":"191","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Ron Carter","titulo":"bass lines","arquivo":"pdf/191.pdf"},
  {"numero":"192","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"SIMANDL, Franz","titulo":"ESTUDOS - Simandl","arquivo":"pdf/192.pdf"},
  {"numero":"193","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"RAY BROWN","titulo":"MÉTODO*-*Ray_Brown*-_Metodo_Per_Contrabasso","arquivo":"pdf/193.pdf"},
  {"numero":"194","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Stuart Hamm","titulo":"Slap,*Pop*&*Tap_for_the_Bass","arquivo":"pdf/194.pdf"},
  {"numero":"195","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Victor Wooten","titulo":"The_best_of_Victor_Wooten","arquivo":"pdf/195.pdf"},
  {"numero":"196","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"WEISKE, Carlos","titulo":"Metodo_Contrabajo_Method_Double_Bass","arquivo":"pdf/196.pdf"},
  {"numero":"197","tipo":"PDF","instrumento":"CONTRABAIXO PIANO","autor":"WEISKE, Carlos","titulo":"Bagatela_Contrabaixo_e_Piano","arquivo":"pdf/197.pdf"},
  {"numero":"198","tipo":"PDF","instrumento":"CONTRABAIXO PIANO FLAUTA PRATOS","autor":"WEISKE, Carlos","titulo":"Punta_Suite*-_Contrabaixo,_Piano,_Flauta_e_Pratos","arquivo":"pdf/198.pdf"},
  {"numero":"199","tipo":"PDF","instrumento":"CONTRABAIXO ACÚSTICO","autor":"Yuri Levitin","titulo":"Sonata_Op.58","arquivo":"pdf/199.pdf"},
  {"numero":"200","tipo":"PDF","instrumento":"CONTRABAIXO ELÉTRICO","autor":"Anônimo","titulo":"Metodo de Jazz","arquivo":"pdf/200.pdf"},
  {"numero":"201","tipo":"PDF","instrumento":"ACORDEON","autor":"Adelar Bertussi","titulo":"Método para acordeon","arquivo":"pdf/201.pdf"},
  {"numero":"202","tipo":"PDF","instrumento":"ACORDEON","autor":"Alencar terra","titulo":"Método para acordeon VOL 1","arquivo":"pdf/202.pdf"},
  {"numero":"203","tipo":"PDF","instrumento":"ACORDEON","autor":"Almagro","titulo":"método","arquivo":"pdf/203.pdf"},
  {"numero":"204","tipo":"PDF","instrumento":"ACORDEON","autor":"ANÔNIMO","titulo":"Curso de Acordeom","arquivo":"pdf/204.pdf"},
  {"numero":"205","tipo":"PDF","instrumento":"ACORDEON","autor":"ANÔNIMO","titulo":"Método Acordeon B-System","arquivo":"pdf/205.pdf"},
  {"numero":"206","tipo":"PDF","instrumento":"ACORDEON","autor":"Antônio Pieroni","titulo":"Método Mirim para Acordeon","arquivo":"pdf/206.pdf"},
  {"numero":"207","tipo":"PDF","instrumento":"ACORDEON","autor":"Anzaghi","titulo":"metodo completo progressivo para acordeon","arquivo":"pdf/207.pdf"},
  {"numero":"208","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Altes","titulo":"Method for the Boehm Flute","arquivo":"pdf/208.pdf"},
  {"numero":"209","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Altes","titulo":"Method for the Boehm Flute","arquivo":"pdf/209.pdf"},
  {"numero":"210","tipo":"PDF","instrumento":"VIOLÃO","autor":"Carlos Campos","titulo":"Salsa_and_Afro_Cuban_Montunos_for_Guitar","arquivo":"pdf/210.pdf"},
  {"numero":"211","tipo":"PDF","instrumento":"VIOLÃO","autor":"Escola Talento Music","titulo":"CURSO DE VIOLAO","arquivo":"pdf/211.pdf"},
  {"numero":"212","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"GARIBOLD, G.","titulo":"MÉTODO 1a Parte","arquivo":"pdf/212.pdf"},
  {"numero":"213","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"GARIBOLD, G.","titulo":"EXERCÍCIOS","arquivo":"pdf/213.pdf"},
  {"numero":"214","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"GARIBOLD, G.","titulo":"ESTUDOS","arquivo":"pdf/214.pdf"},
  {"numero":"215","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_1","arquivo":"pdf/215.pdf"},
  {"numero":"216","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_2","arquivo":"pdf/216.pdf"},
  {"numero":"217","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_3","arquivo":"pdf/217.pdf"},
  {"numero":"218","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_4","arquivo":"pdf/218.pdf"},
  {"numero":"219","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_5","arquivo":"pdf/219.pdf"},
  {"numero":"220","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_6","arquivo":"pdf/220.pdf"},
  {"numero":"221","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_7","arquivo":"pdf/221.pdf"},
  {"numero":"222","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_8","arquivo":"pdf/222.pdf"},
  {"numero":"223","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_9","arquivo":"pdf/223.pdf"},
  {"numero":"224","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_10","arquivo":"pdf/224.pdf"},
  {"numero":"225","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Suzuki","titulo":"Flute_School_Vol_11","arquivo":"pdf/225.pdf"},
  {"numero":"226","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Altamiro Carrilho","titulo":"Chorinhos Didáticos para Flauta","arquivo":"pdf/226.pdf"},
  {"numero":"227","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Bach","titulo":"24 Flute Concert Studies","arquivo":"pdf/227.pdf"},
  {"numero":"228","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Bizet","titulo":"Intermezzo Carmen","arquivo":"pdf/228.pdf"},
  {"numero":"229","tipo":"PDF","instrumento":"VIOLÃO","autor":"Ernesto Hartmann","titulo":"Ponteio_e_Baião_2004_Revisado","arquivo":"pdf/229.pdf"},
  {"numero":"230","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"BOEHM, Theobald","titulo":"24 Capriccios for flute_op.26","arquivo":"pdf/230.pdf"},
  {"numero":"231","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"BOEHM, Theobald","titulo":"Estudos para Flauta Boehm","arquivo":"pdf/231.pdf"},
  {"numero":"232","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Carl Reinecke","titulo":"Concerto.for.Flute.and.Orchestra.in.D.Major.Op.283","arquivo":"pdf/232.pdf"},
  {"numero":"233","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"DROUET, Louis","titulo":"25 Studies For Flute","arquivo":"pdf/233.pdf"},
  {"numero":"234","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"FAURÉ, Grabiel","titulo":"Op 50 - Les Soires Intimes","arquivo":"pdf/234.pdf"},
  {"numero":"235","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Fred Dantas","titulo":"Livro de Exercicios","arquivo":"pdf/235.pdf"},
  {"numero":"236","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Furstenau A. B.","titulo":"24 Estudos para Flauta. Op. 12","arquivo":"pdf/236.pdf"},
  {"numero":"237","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Gilliam e Mccaskill","titulo":"Solos para iniciantes","arquivo":"pdf/237.pdf"},
  {"numero":"238","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Herbert Lindholm","titulo":"peruskuviot1_Teknik_flute","arquivo":"pdf/238.pdf"},
  {"numero":"239","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Herbert Lindholm","titulo":"peruskuviot2_Flute_Tenknik","arquivo":"pdf/239.pdf"},
  {"numero":"240","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Herbert Lindholm","titulo":"peruskuviot3flute_Teknik","arquivo":"pdf/240.pdf"},
  {"numero":"241","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Herbert Lindholm","titulo":"peruskuviot4_flute_teknik","arquivo":"pdf/241.pdf"},
  {"numero":"242","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Jordean Ricardo de Oliveira","titulo":"Programa de curso","arquivo":"pdf/242.pdf"},
  {"numero":"243","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Kohler","titulo":"20 Exercícios melódicos fáceis - Op. 93","arquivo":"pdf/243.pdf"},
  {"numero":"244","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Kohler","titulo":"25 Estudos Românticos","arquivo":"pdf/244.pdf"},
  {"numero":"245","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Laudatorio Musical","titulo":"Posição das Mãos e dos Dedos","arquivo":"pdf/245.pdf"},
  {"numero":"246","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Laudatorio Musical","titulo":"DIGITAÇÃO","arquivo":"pdf/246.pdf"},
  {"numero":"247","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Laudatorio Musical","titulo":"EXERCÍCIOS","arquivo":"pdf/247.pdf"},
  {"numero":"248","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Laudatorio Musical","titulo":"EXERCÍCIOS","arquivo":"pdf/248.pdf"},
  {"numero":"249","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Marcel Moyse","titulo":"EXERCÍCIOS - 25 Estudos de D'Après Czerny","arquivo":"pdf/249.pdf"},
  {"numero":"250","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Marcel Moyse","titulo":"100_Études_Faciles_et_Progressives_d'après_Cramer","arquivo":"pdf/250.pdf"},
  {"numero":"251","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Matthijs Broers","titulo":"Escuchar, Leer & Tocar","arquivo":"pdf/251.pdf"},
  {"numero":"252","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Sávio Araújo","titulo":"Respiração e Embocadura","arquivo":"pdf/252.pdf"},
  {"numero":"253","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Taffanel e Gaubert","titulo":"MÉTODO","arquivo":"pdf/253.pdf"},
  {"numero":"254","tipo":"PDF","instrumento":"FLAUTA TRANSVERSAL","autor":"Yamaha","titulo":"DIGITAÇÃO","arquivo":"pdf/254.pdf"},
  {"numero":"255","tipo":"PDF","instrumento":"TROMPETE","autor":"ADAM, bill","titulo":"adam-trompeta","arquivo":"pdf/255.pdf"},
  {"numero":"256","tipo":"PDF","instrumento":"TROMPETE","autor":"Amadeu Russo","titulo":"todo-trompete-trombone-bombardino","arquivo":"pdf/256.pdf"},
  {"numero":"257","tipo":"PDF","instrumento":"TROMPETE","autor":"Cat Anderson","titulo":"Trumpet_Method","arquivo":"pdf/257.pdf"},
  {"numero":"258","tipo":"PDF","instrumento":"TROMPETE","autor":"CHARLIER, Theo","titulo":"36 Etudes for Trumpet","arquivo":"pdf/258.pdf"},
  {"numero":"259","tipo":"PDF","instrumento":"TROMPETE","autor":"Claude Gordon","titulo":"ESTUDOS","arquivo":"pdf/259.pdf"},
  {"numero":"260","tipo":"PDF","instrumento":"TROMPETE","autor":"Projeto Fortalecimento Musical","titulo":"trompete","arquivo":"pdf/260.pdf"},
  {"numero":"261","tipo":"PDF","instrumento":"TROMPETE","autor":"Digitação","titulo":"trompete","arquivo":"pdf/261.pdf"},
  {"numero":"262","tipo":"PDF","instrumento":"TROMPETE","autor":"GETVHELL, Robert W.","titulo":"First book of practical studies for cornet and trumpet","arquivo":"pdf/262.pdf"},
  {"numero":"263","tipo":"PDF","instrumento":"TROMPETE","autor":"GETVHELL, Robert W.","titulo":"Second boook of practical studies for cornet and trumpet.","arquivo":"pdf/263.pdf"},
  {"numero":"264","tipo":"PDF","instrumento":"TROMPETE","autor":"Herbert Clarke","titulo":"Trumpet Method","arquivo":"pdf/264.pdf"},
  {"numero":"265","tipo":"PDF","instrumento":"TROMPETE","autor":"James Stamp","titulo":"Trumpet method","arquivo":"pdf/265.pdf"},
  {"numero":"266","tipo":"PDF","instrumento":"TROMPETE","autor":"Louis Maggio","titulo":"Advanced Studies (Spanish) Trumpet Method","arquivo":"pdf/266.pdf"},
  {"numero":"267","tipo":"PDF","instrumento":"TROMPETE","autor":"Oskar Bohme","titulo":"24_Melodic_Studies_for_Trumpet_or_Cornet","arquivo":"pdf/267.pdf"},
  {"numero":"268","tipo":"PDF","instrumento":"TROMPETE","autor":"Charles Colin","titulo":"Technical Studies","arquivo":"pdf/268.pdf"},
  {"numero":"269","tipo":"PDF","instrumento":"TROMPETE","autor":"COLETÂNEA","titulo":"Pacote_de_23_Frêvos","arquivo":"pdf/269.pdf"},
  {"numero":"270","tipo":"PDF","instrumento":"INSTRUMENTO Bb","autor":"Paul Hill","titulo":"Combo Orks Book No 1 Bb instruments Trumpet, Tenor Sax. Clarinet","arquivo":"pdf/270.pdf"},
  {"numero":"271","tipo":"PDF","instrumento":"TROMPETE","autor":"Sigmund Hering","titulo":"forty progressive etudes for trumpet","arquivo":"pdf/271.pdf"},
  {"numero":"272","tipo":"PDF","instrumento":"ORGÃO","autor":"SCHNITTKE, Alfred","titulo":"Two_pieces for organ","arquivo":"pdf/272.pdf"},
  {"numero":"273","tipo":"PDF","instrumento":"ORGÃO","autor":"Burt Bacharach","titulo":"[Book]_Collection","arquivo":"pdf/273.pdf"},
  {"numero":"274","tipo":"PDF","instrumento":"ORGÃO VOCAL","autor":"Max Reger","titulo":"Befiehl_dem_Herrn_deine_Wege__Reger__GERMAN_VERSION","arquivo":"pdf/274.pdf"},
  {"numero":"275","tipo":"PDF","instrumento":"ORGÃO VOCAL","autor":"Geistliche Gesange","titulo":"Op.19","arquivo":"pdf/275.pdf"},
  {"numero":"276","tipo":"PDF","instrumento":"INSTRUMENTOS","autor":"SCHNITTKE, Alfred","titulo":"Gavot,_for_glockenspiel,_2_xylophone,_vibraphone,*marimba*&*piano","arquivo":"pdf/276.pdf"},
  {"numero":"277","tipo":"PDF","instrumento":"INSTRUMENTOS","autor":"SCHNITTKE, Alfred","titulo":"3 Madrigals","arquivo":"pdf/277.pdf"},
  {"numero":"278","tipo":"PDF","instrumento":"BAIXO BATERIA","autor":"ANÔNIMO","titulo":"Ritmos Brasileiros","arquivo":"pdf/278.pdf"},
  {"numero":"279","tipo":"PDF","instrumento":"CORDAS","autor":"SCHNITTKE, Alfred","titulo":"2. Streichquartett","arquivo":"pdf/279.pdf"},
  {"numero":"280","tipo":"PDF","instrumento":"CORDAS","autor":"SCHNITTKE, Alfred","titulo":"3. Streichquartett","arquivo":"pdf/280.pdf"},
  {"numero":"281","tipo":"PDF","instrumento":"CORDAS","autor":"RIEDING, Oskar","titulo":"concertino_a-moll_Score_parts op 21","arquivo":"pdf/281.pdf"},
  {"numero":"282","tipo":"PDF","instrumento":"FLAUTA DOCE BAIXO","autor":"ANÔNIMO","titulo":"Método Flauta Doce Baixo","arquivo":"pdf/282.pdf"},
  {"numero":"283","tipo":"PDF","instrumento":"GAITA","autor":"MARCELO MELLO","titulo":"Curso Gaita de Boca","arquivo":"pdf/283.pdf"},
  {"numero":"284","tipo":"PDF","instrumento":"GAITA","autor":"ANÔNIMO","titulo":"Curso_de_Gaita_de_Boca_Completo_2005","arquivo":"pdf/284.pdf"},
  {"numero":"285","tipo":"PDF","instrumento":"GUITARRA VOCAL","autor":"Bob Marley","titulo":"the_Wailers*-*The_Very_Best_of_guitar_songbook","arquivo":"pdf/285.pdf"},
  {"numero":"286","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"REAL BOOK","titulo":"Book","arquivo":"pdf/286.pdf"},
  {"numero":"287","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"REAL BOOK","titulo":"Book","arquivo":"pdf/287.pdf"},
  {"numero":"288","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"REAL BOOK","titulo":"The Real Book Vol I Bb","arquivo":"pdf/288.pdf"},
  {"numero":"289","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"REAL BOOK","titulo":"Jazz_Limited","arquivo":"pdf/289.pdf"},
  {"numero":"290","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"BOOK","titulo":"Tango_Fake_Book","arquivo":"pdf/290.pdf"},
  {"numero":"291","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"SONGBOOK","titulo":"CHORO VOL 1","arquivo":"pdf/291.pdf"},
  {"numero":"292","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"SONGBOOK","titulo":"CHORO VOL 2","arquivo":"pdf/292.pdf"},
  {"numero":"293","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"Cole Porter","titulo":"night and day","arquivo":"pdf/293.pdf"},
  {"numero":"294","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"Mauricio Carrilho","titulo":"Vol 2","arquivo":"pdf/294.pdf"},
  {"numero":"295","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Almir Chediak","titulo":"Songbook Bossa Nova 1","arquivo":"pdf/295.pdf"},
  {"numero":"296","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Almir Chediak","titulo":"Songbook Bossa Nova 4","arquivo":"pdf/296.pdf"},
  {"numero":"297","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Almir Chediak","titulo":"Songbook Bossa Nova 5","arquivo":"pdf/297.pdf"},
  {"numero":"298","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Almir Chediak","titulo":"SONGBOOK_As_101_Melhores_Canções_do_Século_XX","arquivo":"pdf/298.pdf"},
  {"numero":"299","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Almir Chediak","titulo":"SONGBOOK_As_101_Melhores_Canções_do_Século_XX","arquivo":"pdf/299.pdf"},
  {"numero":"300","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Bart Howard","titulo":"PARTITURA","arquivo":"pdf/300.pdf"},
  {"numero":"301","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Chico Buarque","titulo":"Songbook","arquivo":"pdf/301.pdf"},
  {"numero":"302","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Chico Buarque","titulo":"Songbook","arquivo":"pdf/302.pdf"},
  {"numero":"303","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Disney","titulo":"Fake book","arquivo":"pdf/303.pdf"},
  {"numero":"304","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"George Benson","titulo":"Songbook","arquivo":"pdf/304.pdf"},
  {"numero":"305","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Ivan Lins","titulo":"songbook v1","arquivo":"pdf/305.pdf"},
  {"numero":"306","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Tom Jobim","titulo":"Songbook VOL 1","arquivo":"pdf/306.pdf"},
  {"numero":"307","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Tom Jobim","titulo":"Songbook VOL 2","arquivo":"pdf/307.pdf"},
  {"numero":"308","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Tom Jobim","titulo":"Songbook VOL 3","arquivo":"pdf/308.pdf"},
  {"numero":"309","tipo":"PDF","instrumento":"MELODIA CIFRA LETRA","autor":"Tom Jobim","titulo":"BOSSA NOVA - Vol_98","arquivo":"pdf/309.pdf"},
  {"numero":"310","tipo":"PDF","instrumento":"MELODIA LETRA","autor":"Domingos Morais","titulo":"Cancioneiro","arquivo":"pdf/310.pdf"},
  {"numero":"311","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"REAL BOOK","titulo":"The_Real_Book_of_Jazz_Volume_I","arquivo":"pdf/311.pdf","conta":"CONTA_C"},
  {"numero":"312","tipo":"PDF","instrumento":"GUITARRA","autor":"FELIX SCHELL","titulo":"Hot Session","arquivo":"pdf/312.pdf"},
  {"numero":"313","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"Book","titulo":"Brazilian Jazz Real Book","arquivo":"pdf/313.pdf"},
  {"numero":"314","tipo":"PDF","instrumento":"MELODIA CIFRA","autor":"Vinicius de Moraes","titulo":"Songbook vols 1, 2 e 3","arquivo":"pdf/314.pdf"},
  {"numero":"315","tipo":"PDF","instrumento":"VIOLINO","autor":"Schmoll A.","titulo":"Metodo_Para_Violino","arquivo":"pdf/315.pdf"},
  {"numero":"316","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Alard_School_of_Violin*[Scuola_del_Violino_Scale_ed_Esercizi]_Scales_and_Exercises_Extract_from_Method","arquivo":"pdf/316.pdf"},
  {"numero":"317","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Le_sourire__scherzando_Arr._for_Violin_Piano_by_Vidas_Violin_Part","arquivo":"pdf/317.pdf"},
  {"numero":"318","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"ecole","arquivo":"pdf/318.pdf"},
  {"numero":"319","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"escuela_violin","arquivo":"pdf/319.pdf"},
  {"numero":"320","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Pieces_caracteristiques_No13_PS_rsl","arquivo":"pdf/320.pdf"},
  {"numero":"321","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Pieces_caracteristiques_No13_VnPt_rsl","arquivo":"pdf/321.pdf"},
  {"numero":"322","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Op.2","arquivo":"pdf/322.pdf"},
  {"numero":"323","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Violin_Concerto_No1_Violin","arquivo":"pdf/323.pdf"},
  {"numero":"324","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"10 Etudes_artistiques_Op 19_Vn_rsl","arquivo":"pdf/324.pdf"},
  {"numero":"325","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Souvenirs_de_Mozart_vl.and_small_orchestra_parts","arquivo":"pdf/325.pdf"},
  {"numero":"326","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"2nd_Symphonie_Concertante_for_2_Violins_and_Orch__Op.33_vln1","arquivo":"pdf/326.pdf"},
  {"numero":"327","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"violin","arquivo":"pdf/327.pdf"},
  {"numero":"328","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Symphonie_concertante_No.2_Op.33_violin2_part","arquivo":"pdf/328.pdf"},
  {"numero":"329","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"violin_II","arquivo":"pdf/329.pdf"},
  {"numero":"330","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Symphonie_concertante_No.3_Op.34 bis_violin1_part","arquivo":"pdf/330.pdf"},
  {"numero":"331","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"24_Etuden-Capricen_Heft_1_Op. 41","arquivo":"pdf/331.pdf"},
  {"numero":"332","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"24_Etudes_Caprices__Op. 41 parte 2","arquivo":"pdf/332.pdf"},
  {"numero":"333","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Aragonesa_op. 42_Violin","arquivo":"pdf/333.pdf"},
  {"numero":"334","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Al_rigo_vl_cmplt","arquivo":"pdf/334.pdf"},
  {"numero":"335","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Faust_op. 47","arquivo":"pdf/335.pdf"},
  {"numero":"336","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"art_mod_op. 53","arquivo":"pdf/336.pdf"},
  {"numero":"337","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Ernani_op. 54","arquivo":"pdf/337.pdf"},
  {"numero":"338","tipo":"PDF","instrumento":"VIOLINO","autor":"ALARD, Delphin.","titulo":"Echo_des_Alpes_op. 60","arquivo":"pdf/338.pdf"},
  {"numero":"339","tipo":"PDF","instrumento":"VIOLINO","autor":"BAILLOT, Pierre","titulo":"metodo_per_violino","arquivo":"pdf/339.pdf"},
  {"numero":"340","tipo":"PDF","instrumento":"VIOLINO","autor":"BÉRIOT, De","titulo":"Method_for_the_Violin_Pt 1","arquivo":"pdf/340.pdf"},
  {"numero":"341","tipo":"PDF","instrumento":"VIOLINO","autor":"BÉRIOT, Ch","titulo":"Methode_de_violon_Part2_Ru_rsl","arquivo":"pdf/341.pdf"},
  {"numero":"342","tipo":"PDF","instrumento":"VIOLINO","autor":"CAMPAGNOLI, Bartolomeo","titulo":"30_Preludes_for_violin","arquivo":"pdf/342.pdf"},
  {"numero":"343","tipo":"PDF","instrumento":"VIOLINO","autor":"CAMPAGNOLI, Bartolomeo","titulo":"Method_1","arquivo":"pdf/343.pdf"},
  {"numero":"344","tipo":"PDF","instrumento":"VIOLINO","autor":"CASORTI, A.","titulo":"ESTUDO_DE_ARCO_PARA_VIOLINO","arquivo":"pdf/344.pdf"},
  {"numero":"345","tipo":"PDF","instrumento":"VIOLINO","autor":"CORRETTE","titulo":"metodo_de_violino","arquivo":"pdf/345.pdf"},
  {"numero":"346","tipo":"PDF","instrumento":"VIOLINO","autor":"CZERNY","titulo":"op 153 parts","arquivo":"pdf/346.pdf"},
  {"numero":"347","tipo":"PDF","instrumento":"VIOLINO","autor":"Eberhardt Goby","titulo":"Violin_School._Vol._1","arquivo":"pdf/347.pdf"},
  {"numero":"348","tipo":"PDF","instrumento":"VIOLINO","autor":"Eberhardt Goby","titulo":"Eberhardt Goby","arquivo":"pdf/348.pdf"},
  {"numero":"349","tipo":"PDF","instrumento":"VIOLINO","autor":"EDINBURGH","titulo":"repository_1","arquivo":"pdf/349.pdf"},
  {"numero":"350","tipo":"PDF","instrumento":"VIOLINO","autor":"EDINBURGH","titulo":"repository_2","arquivo":"pdf/350.pdf"},
  {"numero":"351","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_1","arquivo":"pdf/351.pdf"},
  {"numero":"352","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_2","arquivo":"pdf/352.pdf"},
  {"numero":"353","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_3","arquivo":"pdf/353.pdf"},
  {"numero":"354","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_4","arquivo":"pdf/354.pdf"},
  {"numero":"355","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_5","arquivo":"pdf/355.pdf"},
  {"numero":"356","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Book_6","arquivo":"pdf/356.pdf"},
  {"numero":"357","tipo":"PDF","instrumento":"VIOLINO","autor":"FERRARA, Bernardo","titulo":"Lo_Studio_del_Violino","arquivo":"pdf/357.pdf"},
  {"numero":"358","tipo":"PDF","instrumento":"VIOLINO","autor":"FISCHER, Simon","titulo":"método Livro indicado para Principantes","arquivo":"pdf/358.pdf"},
  {"numero":"359","tipo":"PDF","instrumento":"VIOLINO","autor":"FLESCH, Carl","titulo":"Basic_Studies_for_Violin","arquivo":"pdf/359.pdf"},
  {"numero":"360","tipo":"PDF","instrumento":"VIOLINO","autor":"FLESCH, Carl","titulo":"escala","arquivo":"pdf/360.pdf"},
  {"numero":"361","tipo":"PDF","instrumento":"VIOLINO","autor":"GALAMIAN, Ivan","titulo":"Tecnica_Contemporanea_del_Violino*(Scale*&*Arpeggi)","arquivo":"pdf/361.pdf"},
  {"numero":"362","tipo":"PDF","instrumento":"VIOLINO","autor":"TARTINI, Giuseppe","titulo":"The_art_of_bowing","arquivo":"pdf/362.pdf"},
  {"numero":"363","tipo":"PDF","instrumento":"VIOLINO","autor":"TARTINI, Giuseppe","titulo":"ARCO - Exercícios - 50 Exercícios","arquivo":"pdf/363.pdf"},
  {"numero":"364","tipo":"PDF","instrumento":"VIOLINO","autor":"KASYSER, H.E.","titulo":"op.44","arquivo":"pdf/364.pdf"},
  {"numero":"365","tipo":"PDF","instrumento":"VIOLINO","autor":"SITT, Hans","titulo":"Op.32","arquivo":"pdf/365.pdf"},
  {"numero":"366","tipo":"PDF","instrumento":"VIOLINO","autor":"SITT, Hans","titulo":"Op.32","arquivo":"pdf/366.pdf"},
  {"numero":"367","tipo":"PDF","instrumento":"VIOLINO","autor":"SITT, Hans","titulo":"Op.32","arquivo":"pdf/367.pdf"},
  {"numero":"368","tipo":"PDF","instrumento":"VIOLINO","autor":"SITT, Hans","titulo":"Estudos_de_Escalas","arquivo":"pdf/368.pdf"},
  {"numero":"369","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_1","arquivo":"pdf/369.pdf"},
  {"numero":"370","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_2_The_1st__2nd_and_3rd_positions","arquivo":"pdf/370.pdf"},
  {"numero":"371","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_3","arquivo":"pdf/371.pdf"},
  {"numero":"372","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_4_Elementary_double_stopping_and_chords","arquivo":"pdf/372.pdf"},
  {"numero":"373","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_5_The_art_of_shifting","arquivo":"pdf/373.pdf"},
  {"numero":"374","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_6_Tone_production_and_phrasing","arquivo":"pdf/374.pdf"},
  {"numero":"375","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_7_Rapidity_of_fingering","arquivo":"pdf/375.pdf"},
  {"numero":"376","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_8_Bravura_double_stopping","arquivo":"pdf/376.pdf"},
  {"numero":"377","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_9_The_art_of_bowing","arquivo":"pdf/377.pdf"},
  {"numero":"378","tipo":"PDF","instrumento":"VIOLINO","autor":"HENLEY, William","titulo":"Ecole moderne_du_violon__Modern_violin_school_Op51_bk_10_Chords_and_part-playing","arquivo":"pdf/378.pdf"},
  {"numero":"379","tipo":"PDF","instrumento":"VIOLINO","autor":"SCHRADIECK, Henry","titulo":"School_of_Violin_Technics_Bk.1","arquivo":"pdf/379.pdf"},
  {"numero":"380","tipo":"PDF","instrumento":"VIOLINO","autor":"SCHRADIECK, Henry","titulo":"School_of_Violin_Technics_Bk.2","arquivo":"pdf/380.pdf"},
  {"numero":"381","tipo":"PDF","instrumento":"VIOLINO","autor":"SCHRADIECK, Henry","titulo":"School_of_Violin_Technics_Bk.3","arquivo":"pdf/381.pdf"},
  {"numero":"382","tipo":"PDF","instrumento":"VIOLINO","autor":"SCHRADIECK, Henry","titulo":"Complete_Scale_Studies","arquivo":"pdf/382.pdf"},
  {"numero":"383","tipo":"PDF","instrumento":"VIOLNO","autor":"HERMANN, Friedr","titulo":"violinschule","arquivo":"pdf/383.pdf"},
  {"numero":"384","tipo":"PDF","instrumento":"VIOLINO","autor":"HOHMANN, C. H.","titulo":"Metodo pratico","arquivo":"pdf/384.pdf"},
  {"numero":"385","tipo":"PDF","instrumento":"VIOLINO","autor":"HOHMANN, C. H.","titulo":"Metodo pratico","arquivo":"pdf/385.pdf"},
  {"numero":"386","tipo":"PDF","instrumento":"VIOLINO","autor":"HOHMANN, C. H.","titulo":"Metodo pratico","arquivo":"pdf/386.pdf"},
  {"numero":"387","tipo":"PDF","instrumento":"PIANO","autor":"Livro","titulo":"Edna Mae Burnam","arquivo":"pdf/387.pdf"},
  {"numero":"388","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"ubungen-fur-die-noten-exercises-for-the-notes-9690","arquivo":"pdf/388.pdf"},
  {"numero":"389","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"60 estudos Barroso Netto","arquivo":"pdf/389.pdf"},
  {"numero":"390","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"partitura avulsa n13","arquivo":"pdf/390.pdf"},
  {"numero":"391","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"22_rondinos_ed_relling","arquivo":"pdf/391.pdf"},
  {"numero":"392","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"Czerny - Selected_Pianoforte_Studies - Book_I - Part_I*&*II","arquivo":"pdf/392.pdf"},
  {"numero":"393","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"studio_generale*-_enciclopedia_di_passi_brillanti","arquivo":"pdf/393.pdf"},
  {"numero":"394","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"variazioni_sul_sehnsucht_valzer_beethoven","arquivo":"pdf/394.pdf"},
  {"numero":"395","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"musikalisches_pfennigmagazin_cah1_nr15","arquivo":"pdf/395.pdf"},
  {"numero":"396","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"rondoletto_uber_robert_le_diable_meyerbeer","arquivo":"pdf/396.pdf"},
  {"numero":"397","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"rondoletto_uber_zwei_motife_aus_der_oper_die_belagerung_von_corinth_von_rossini","arquivo":"pdf/397.pdf"},
  {"numero":"398","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"Bellini_I_Puritani","arquivo":"pdf/398.pdf"},
  {"numero":"399","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"musikalisches_pfennig-magazin_n9","arquivo":"pdf/399.pdf"},
  {"numero":"400","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"musikalisches_pfennig-magazin_n36","arquivo":"pdf/400.pdf"},
  {"numero":"401","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"haydn_czerny_die_schopfung","arquivo":"pdf/401.pdf"},
  {"numero":"402","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"Quiet_Thoughts","arquivo":"pdf/402.pdf"},
  {"numero":"403","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"Letters_to_a_Young_Lady","arquivo":"pdf/403.pdf"},
  {"numero":"404","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"3 rondosThe_Legacy","arquivo":"pdf/404.pdf"},
  {"numero":"405","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"Recreations-Heft_I","arquivo":"pdf/405.pdf"},
  {"numero":"406","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"WIMA.c7c1-Allegretto-","arquivo":"pdf/406.pdf"},
  {"numero":"407","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"WIMA.952c-Andante","arquivo":"pdf/407.pdf"},
  {"numero":"408","tipo":"PDF","instrumento":"PIANO","autor":"CZERNY, Carl","titulo":"WIMA.0429-Uebung-R.Hand","arquivo":"pdf/408.pdf"}



    



]; // Fechado corretamente apenas uma vez
